// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// createSimilarityMat
arma::mat createSimilarityMat(arma::umat allocations);
RcppExport SEXP _tagmReDraft_createSimilarityMat(SEXP allocationsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::umat >::type allocations(allocationsSEXP);
    rcpp_result_gen = Rcpp::wrap(createSimilarityMat(allocations));
    return rcpp_result_gen;
END_RCPP
}
// squaredExponentialFunction
double squaredExponentialFunction(double amplitude, double length, int i, int j);
RcppExport SEXP _tagmReDraft_squaredExponentialFunction(SEXP amplitudeSEXP, SEXP lengthSEXP, SEXP iSEXP, SEXP jSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type amplitude(amplitudeSEXP);
    Rcpp::traits::input_parameter< double >::type length(lengthSEXP);
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< int >::type j(jSEXP);
    rcpp_result_gen = Rcpp::wrap(squaredExponentialFunction(amplitude, length, i, j));
    return rcpp_result_gen;
END_RCPP
}
// sampleMean
arma::vec sampleMean(arma::mat X);
RcppExport SEXP _tagmReDraft_sampleMean(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(sampleMean(X));
    return rcpp_result_gen;
END_RCPP
}
// calcSampleCov
arma::mat calcSampleCov(arma::mat data, arma::vec sample_mean, arma::uword N, arma::uword P);
RcppExport SEXP _tagmReDraft_calcSampleCov(SEXP dataSEXP, SEXP sample_meanSEXP, SEXP NSEXP, SEXP PSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sample_mean(sample_meanSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type N(NSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type P(PSEXP);
    rcpp_result_gen = Rcpp::wrap(calcSampleCov(data, sample_mean, N, P));
    return rcpp_result_gen;
END_RCPP
}
// gammaLogLikelihood
double gammaLogLikelihood(double x, double shape, double rate);
RcppExport SEXP _tagmReDraft_gammaLogLikelihood(SEXP xSEXP, SEXP shapeSEXP, SEXP rateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type shape(shapeSEXP);
    Rcpp::traits::input_parameter< double >::type rate(rateSEXP);
    rcpp_result_gen = Rcpp::wrap(gammaLogLikelihood(x, shape, rate));
    return rcpp_result_gen;
END_RCPP
}
// invGammaLogLikelihood
double invGammaLogLikelihood(double x, double shape, double scale);
RcppExport SEXP _tagmReDraft_invGammaLogLikelihood(SEXP xSEXP, SEXP shapeSEXP, SEXP scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type shape(shapeSEXP);
    Rcpp::traits::input_parameter< double >::type scale(scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(invGammaLogLikelihood(x, shape, scale));
    return rcpp_result_gen;
END_RCPP
}
// wishartLogLikelihood
double wishartLogLikelihood(arma::mat X, arma::mat V, double n, arma::uword P);
RcppExport SEXP _tagmReDraft_wishartLogLikelihood(SEXP XSEXP, SEXP VSEXP, SEXP nSEXP, SEXP PSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type V(VSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type P(PSEXP);
    rcpp_result_gen = Rcpp::wrap(wishartLogLikelihood(X, V, n, P));
    return rcpp_result_gen;
END_RCPP
}
// invWishartLogLikelihood
double invWishartLogLikelihood(arma::mat X, arma::mat Psi, double nu, arma::uword P);
RcppExport SEXP _tagmReDraft_invWishartLogLikelihood(SEXP XSEXP, SEXP PsiSEXP, SEXP nuSEXP, SEXP PSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Psi(PsiSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type P(PSEXP);
    rcpp_result_gen = Rcpp::wrap(invWishartLogLikelihood(X, Psi, nu, P));
    return rcpp_result_gen;
END_RCPP
}
// mvtLogLikelihood
double mvtLogLikelihood(arma::vec x, arma::vec mu, arma::mat Sigma, double nu);
RcppExport SEXP _tagmReDraft_mvtLogLikelihood(SEXP xSEXP, SEXP muSEXP, SEXP SigmaSEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu(muSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(mvtLogLikelihood(x, mu, Sigma, nu));
    return rcpp_result_gen;
END_RCPP
}
// pNorm
double pNorm(arma::vec x, arma::vec mu, arma::mat Sigma, bool is_sympd);
RcppExport SEXP _tagmReDraft_pNorm(SEXP xSEXP, SEXP muSEXP, SEXP SigmaSEXP, SEXP is_sympdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu(muSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< bool >::type is_sympd(is_sympdSEXP);
    rcpp_result_gen = Rcpp::wrap(pNorm(x, mu, Sigma, is_sympd));
    return rcpp_result_gen;
END_RCPP
}
// gaussianLogLikelihood
double gaussianLogLikelihood(arma::vec x, arma::vec mu, arma::vec std_dev);
RcppExport SEXP _tagmReDraft_gaussianLogLikelihood(SEXP xSEXP, SEXP muSEXP, SEXP std_devSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu(muSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type std_dev(std_devSEXP);
    rcpp_result_gen = Rcpp::wrap(gaussianLogLikelihood(x, mu, std_dev));
    return rcpp_result_gen;
END_RCPP
}
// runMDI
Rcpp::List runMDI(arma::uword R, arma::uword thin, arma::field<arma::mat> Y, arma::uvec K, arma::uvec mixture_types, arma::uvec outlier_types, arma::umat labels, arma::umat fixed, arma::field< arma::vec > proposal_windows);
RcppExport SEXP _tagmReDraft_runMDI(SEXP RSEXP, SEXP thinSEXP, SEXP YSEXP, SEXP KSEXP, SEXP mixture_typesSEXP, SEXP outlier_typesSEXP, SEXP labelsSEXP, SEXP fixedSEXP, SEXP proposal_windowsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::uword >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< arma::field<arma::mat> >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type mixture_types(mixture_typesSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type outlier_types(outlier_typesSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type fixed(fixedSEXP);
    Rcpp::traits::input_parameter< arma::field< arma::vec > >::type proposal_windows(proposal_windowsSEXP);
    rcpp_result_gen = Rcpp::wrap(runMDI(R, thin, Y, K, mixture_types, outlier_types, labels, fixed, proposal_windows));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tagmReDraft_createSimilarityMat", (DL_FUNC) &_tagmReDraft_createSimilarityMat, 1},
    {"_tagmReDraft_squaredExponentialFunction", (DL_FUNC) &_tagmReDraft_squaredExponentialFunction, 4},
    {"_tagmReDraft_sampleMean", (DL_FUNC) &_tagmReDraft_sampleMean, 1},
    {"_tagmReDraft_calcSampleCov", (DL_FUNC) &_tagmReDraft_calcSampleCov, 4},
    {"_tagmReDraft_gammaLogLikelihood", (DL_FUNC) &_tagmReDraft_gammaLogLikelihood, 3},
    {"_tagmReDraft_invGammaLogLikelihood", (DL_FUNC) &_tagmReDraft_invGammaLogLikelihood, 3},
    {"_tagmReDraft_wishartLogLikelihood", (DL_FUNC) &_tagmReDraft_wishartLogLikelihood, 4},
    {"_tagmReDraft_invWishartLogLikelihood", (DL_FUNC) &_tagmReDraft_invWishartLogLikelihood, 4},
    {"_tagmReDraft_mvtLogLikelihood", (DL_FUNC) &_tagmReDraft_mvtLogLikelihood, 4},
    {"_tagmReDraft_pNorm", (DL_FUNC) &_tagmReDraft_pNorm, 4},
    {"_tagmReDraft_gaussianLogLikelihood", (DL_FUNC) &_tagmReDraft_gaussianLogLikelihood, 3},
    {"_tagmReDraft_runMDI", (DL_FUNC) &_tagmReDraft_runMDI, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_tagmReDraft(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
