# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

runAltMDI <- function(R, thin, Y, K, mixture_types, outlier_types, labels, fixed) {
    .Call(`_tagmReDraft_runAltMDI`, R, thin, Y, K, mixture_types, outlier_types, labels, fixed)
}

#' @title Create Similarity Matrix
#' @description Constructs a similarity matrix of the pairwise coclustering 
#' rate.
#' @param allocations Matrix of sampled partitions. Columns correspond to 
#' items/samples being clustered, each row is a sampled partition.//' 
#' @return A symmetric n x n matrix (for n rows in cluster record) describing 
#' the fraction of iterations for which each pairwise combination of points are
#' assigned the same label.
#' @export
createSimilarityMat <- function(allocations) {
    .Call(`_tagmReDraft_createSimilarityMat`, allocations)
}

#' title Propose new non-negative value
#' description Propose new non-negative for sampling.
#' param x Current value to be proposed
#' param window The proposal window
#' return new double
NULL

#' title The Inverse Gamma Distribution
#' description Random generation from the inverse Gamma distribution.
#' param shape Shape parameter.
#' param rate Rate parameter.
#' return Sample from invGamma(shape, rate).
NULL

#' title The Inverse Gamma Distribution
#' description Random generation from the inverse Gamma distribution.
#' param N Number of samples to draw.
#' param shape Shape parameter.
#' param rate Rate parameter.
#' return Sample from invGamma(shape, rate).
NULL

#' title The Gamma Distribution
#' description Random generation from the Gamma distribution.
#' param shape Shape parameter.
#' param rate Rate parameter.
#' return Sample from Gamma(shape, rate).
NULL

#' title The Gamma Distribution
#' description Random generation from the Gamma distribution.
#' param N Number of samples to draw.
#' param shape Shape parameter.
#' param rate Rate parameter.
#' return N samples from Gamma(shape, rate).
NULL

#' title The Half-Cauchy Distribution
#' description Random generation from the Half-Cauchy distribution.
#' See https://en.wikipedia.org/wiki/Cauchy_distribution#Related_distributions
#' param mu Location parameter.
#' param scale Scale parameter.
#' return Sample from HalfCauchy(mu, scale).
NULL

#' title The Half-Cauchy Distribution
#' description Random generation from the Half-Cauchy distribution.
#' See https://en.wikipedia.org/wiki/Cauchy_distribution#Related_distributions
#' param N The number of samples to draw
#' param mu Location parameter.
#' param scale Scale parameter.
#' return Sample from HalfCauchy(mu, scale).
NULL

#' title The Half-Cauchy Distribution
#' description Calculates the pdf of the Half-Cauchy distribution for value x.
#' See https://en.wikipedia.org/wiki/Cauchy_distribution#Related_distributions
#' param x Value to calculate the probability density of.
#' param mu Location parameter.
#' param scale Scale parameter.
#' return Sample from HalfCauchy(mu, scale).
NULL

#' title The Beta Distribution
#' description Random generation from the Beta distribution.
#' See https://en.wikipedia.org/wiki/Beta_distribution#Related_distributions.
#' Samples from a Beta distribution based using two independent gamma
#' distributions.
#' param a Shape parameter.
#' param b Shape parameter.
#' return Sample from Beta(a, b).
NULL

#' title The Beta Distribution
#' description Random generation from the Beta distribution.
#' See https://en.wikipedia.org/wiki/Beta_distribution#Related_distributions.
#' Samples from a Beta distribution based using two independent gamma
#' distributions.
#' param n The number of samples to draw.
#' param a Shape parameter.
#' param b Shape parameter.
#' return Sample from Beta(a, b).
NULL

#' title Metropolis acceptance step
#' description Given a probaility, randomly accepts by sampling from a uniform 
#' distribution.
#' param acceptance_prob Double between 0 and 1.
#' return Boolean indicating acceptance.
NULL

#' title Squared exponential function
#' description The squared exponential function as used in a covariance kernel.
#' param amplitude The amplitude parameter (double)
#' param length The length parameter (double)
#' param i Time point (unsigned integer)
#' param j Time point (unsigned integer)
#' return Squared exponential metric of (i, j)
NULL

#' title Sample mean
#' description calculate the sample mean of a matrix X.
#' param X Matrix
#' return Vector of the column means of X.
NULL

#' title Calculate sample covariance
#' description Returns the unnormalised sample covariance. Required as
#' arma::cov() does not work for singletons.
#' param data Data in matrix format
#' param sample_mean Sample mean for data
#' param n The number of samples in data
#' param n_col The number of columns in data
#' return One of the parameters required to calculate the posterior of the
#'  Multivariate normal with uknown mean and covariance (the unnormalised
#'  sample covariance).
NULL

#' @title Propose new non-negative value
#' @description Propose new non-negative for sampling.
#' @param x Current value to be proposed
#' @param window The proposal window
#' @return new double
NULL

#' @title The Inverse Gamma Distribution
#' @description Random generation from the inverse Gamma distribution.
#' @param shape Shape parameter.
#' @param rate Rate parameter.
#' @return Sample from invGamma(shape, rate).
NULL

#' @title The Inverse Gamma Distribution
#' @description Random generation from the inverse Gamma distribution.
#' @param N Number of samples to draw.
#' @param shape Shape parameter.
#' @param rate Rate parameter.
#' @return Sample from invGamma(shape, rate).
NULL

#' @title The Gamma Distribution
#' @description Random generation from the Gamma distribution.
#' @param shape Shape parameter.
#' @param rate Rate parameter.
#' @return Sample from Gamma(shape, rate).
NULL

#' @title The Gamma Distribution
#' @description Random generation from the Gamma distribution.
#' @param N Number of samples to draw.
#' @param shape Shape parameter.
#' @param rate Rate parameter.
#' @return N samples from Gamma(shape, rate).
NULL

#' @title The Half-Cauchy Distribution
#' @description Random generation from the Half-Cauchy distribution.
#' See https://en.wikipedia.org/wiki/Cauchy_distribution#Related_distributions
#' @param mu Location parameter.
#' @param scale Scale parameter.
#' @return Sample from HalfCauchy(mu, scale).
NULL

#' @title The Half-Cauchy Distribution
#' @description Calculates the pdf of the Half-Cauchy distribution for value x.
#' See https://en.wikipedia.org/wiki/Cauchy_distribution#Related_distributions
#' @param x Value to calculate the probability density of.
#' @param mu Location parameter.
#' @param scale Scale parameter.
#' @return Sample from HalfCauchy(mu, scale).
NULL

#' @title The Beta Distribution
#' @description Random generation from the Beta distribution.
#' See https://en.wikipedia.org/wiki/Beta_distribution#Related_distributions.
#' Samples from a Beta distribution based using two independent gamma
#' distributions.
#' @param a Shape parameter.
#' @param b Shape parameter.
#' @return Sample from Beta(a, b).
NULL

#' @title The Beta Distribution
#' @description Random generation from the Beta distribution.
#' See https://en.wikipedia.org/wiki/Beta_distribution#Related_distributions.
#' Samples from a Beta distribution based using two independent gamma
#' distributions.
#' @param n The number of samples to draw.
#' @param a Shape parameter.
#' @param b Shape parameter.
#' @return Sample from Beta(a, b).
NULL

#' @title Calculate sample covariance
#' @description Returns the unnormalised sample covariance. Required as
#' arma::cov() does not work for singletons.
#' @param data Data in matrix format
#' @param sample_mean Sample mean for data
#' @param n The number of samples in data
#' @param n_col The number of columns in data
#' @return One of the parameters required to calculate the posterior of the
#'  Multivariate normal with uknown mean and covariance (the unnormalised
NULL

#' @title Metropolis acceptance step
#' @description Given a probaility, randomly accepts by sampling from a uniform 
#' distribution.
#' @param acceptance_prob Double between 0 and 1.
#' @return Boolean indicating acceptance.
NULL

#' @title Double approximately equal
#' @description Compare two doubles in a way that makes sense.
#' @param x first double considered
#' @param y double compared to x
#' @param precision double of the tolerance of disagreement between x and y.
#' @return bool indicating if the absolute difference between x and y is less 
#' than precision.
NULL

#' @title Sample mean
#' @description calculate the sample mean of a matrix X.
#' @param X Matrix
#' @return Vector of the column means of X.
NULL

#' @title Round matrix
#' @description Round a matrix to n_places decimal places.
#' @param X Matrix
#' @param n_places Integer - number of decimal places to round to
#' @return Matrix X round to n_places decimal places.
NULL

#' @title Choose
#' @description N choose K for binomial coefficient
#' @param n unsigned int (greater than k)
#' @param k unsigned int 
#' @return n choose k
NULL

#' @title Log Choose
#' @description Log transform of N choose K for binomial coefficient
#' @param n unsigned int (greater than k)
#' @param k unsigned int 
#' @return n choose k
NULL

#' @title Squared exponential function
#' @description The squared exponential function as used in a covariance kernel.
#' @param amplitude The amplitude parameter (double)
#' @param length The length parameter (double)
#' @param i Time point (unsigned integer)
#' @param j Time point (unsigned integer)
#' @return Boolean indicating acceptance.
squaredExponentialFunction <- function(amplitude, length, i, j) {
    .Call(`_tagmReDraft_squaredExponentialFunction`, amplitude, length, i, j)
}

#' @title Gamma log-likelihood
#' @description The log-likelihood of each element of a vector in a Gamma 
#' distribution parametrised with a shape and rate.
#' @param x - vector; the values to calculate the likelihood of.
#' @param shape - double; the shape of the Gamma distribution.
#' @param rate - double; the rate of the Gamma distribution
#' @return the log-likelihood of x in a Gamma with parameters shape and rate.
NULL

#' @title Gaussian log-likelihood
#' @description The log-likelihood function for a point in the univariate 
#' Gaussian distribution.
#' @param x - double; the sample to calculate the log likelihood of.
#' @param mu - double; the mean parameter of the Gaussian distribution.
#' @param sigma_2 - double; the standard deviation of the Gaussian distribution.
#' @return the normalised log-likelihood of x in a Gaussian distribution with 
#' parameters mu, sigma_2.
NULL

#' @title Gamma log-likelihood
#' @description Used in calculating model probability in Metropolis-Hastings 
#' algorithm when proposals are from the Gamma distribution.
#' @param x - double; the value to calculate the likelihood of.
#' @param shape - double; the shape of the Gamma distribution.
#' @param rate - double; the rate of the Gamma distribution
#' @return the log-likelihood of x in a Gamma with parameters shape 
#' and rate.
gammaLogLikelihood <- function(x, shape, rate) {
    .Call(`_tagmReDraft_gammaLogLikelihood`, x, shape, rate)
}

#' @title Inverse gamma log-likelihood
#' @description Used in calculating model probability in Metropolis-Hastings 
#' algorithm when proposals are from the inverse-Gamma distribution.
#' @param x - double; the value to calculate the likelihood of.
#' @param shape - double; the shape of the inverse-Gamma distribution.
#' @param scale - double; the scale of the inverse-Gamma distribution
#' @return the unnormalised log-likelihood of x in a inverse-Gamma with parameters 
#' shape and scale.
invGammaLogLikelihood <- function(x, shape, scale) {
    .Call(`_tagmReDraft_invGammaLogLikelihood`, x, shape, scale)
}

#' @title Wishart log-likelihood
#' @description Used in calculating model probability in Metropolis-Hastings 
#' algorithm when proposals are from the Wishart distribution.
#' @param X - matrix; the matrix to calculate the likelihood of.
#' @param V - matrix; the scale of the Wishart distribution.
#' @param n - double; the degrees of freedom for the Wishart distribution.
#' @param P - unsigned integer; the dimension of X.
#' @return the unnormalised log-likelihood of X in a Wishart with parameters V 
#' and n.
wishartLogLikelihood <- function(X, V, n, P) {
    .Call(`_tagmReDraft_wishartLogLikelihood`, X, V, n, P)
}

#' @title Inverse-Wishart log-likelihood
#' @description Used in calculating model probability in Metropolis-Hastings 
#' algorithm when proposals are from the Wishart distribution.
#' @param X - matrix; the matrix to calculate the likelihood of.
#' @param Psi - matrix; the scale of the inverse-Wishart distribution.
#' @param nu - double; the degrees of freedom for the inverse-Wishart distribution.
#' @param P - unsigned integer; the dimension of X.
#' @return the unnormalised log-likelihood of X in a inverse-Wishart with parameters Psi 
#' and nu.
invWishartLogLikelihood <- function(X, Psi, nu, P) {
    .Call(`_tagmReDraft_invWishartLogLikelihood`, X, Psi, nu, P)
}

#' @title Multivariate t log-likelihood
#' @description The log-likelihood function for a point in the multivariate t 
#' (MVT) distribution.
#' @param x - vector; the sample to calculate the log likelihood of.
#' @param mu - vector; the mean parameter of the MVT distribution.
#' @param Sigma - matrix; the scale matrix of the MVT distribution.
#' @param nu - double; the degrees of freedom for the MVT distribution.
#' @return the normalised log-likelihood of x in a MVT distribution with 
#' parameters mu, Sigma and nu.
mvtLogLikelihood <- function(x, mu, Sigma, nu) {
    .Call(`_tagmReDraft_mvtLogLikelihood`, x, mu, Sigma, nu)
}

#' @title Multivariate Normal log-likelihood
#' @description The log-likelihood function for a point in the multivariate 
#' Normal (MVN) distribution.
#' @param x - vector; the sample to calculate the log likelihood of.
#' @param mu - vector; the mean parameter of the MVN distribution.
#' @param Sigma - matrix; the covariance matrix of the MVN distribution.
#' @param is_sympd - boolean; is the covariance matrix positive definite (
#' calculations are faster if this is the case).
#' @return the normalised log-likelihood of x in a MVN distribution with 
#' parameters mu, Sigma.
pNorm <- function(x, mu, Sigma, is_sympd = TRUE) {
    .Call(`_tagmReDraft_pNorm`, x, mu, Sigma, is_sympd)
}

